services:
  postgres:
    container_name: crm.postgres
    image: postgres:16.4
    hostname: postgres
    env_file:
      - .env.local
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_SSL_MODE=${POSTGRES_SSL_MODE}
    ports:
      - 5432:5432
    volumes:
      - .:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U dev -d crm'" ]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 30s
